#!/bin/sh

cat <<EOF > /usr/share/nginx/html/runtime-env.js
window.REACT_APP_ETH_SYMBOL = "$REACT_APP_ETH_SYMBOL";
window.REACT_APP_BASE_CHAIN = "$REACT_APP_BASE_CHAIN";
window.REACT_APP_ROLLUP = "$REACT_APP_ROLLUP";
window.REACT_APP_CONNECT_WALLET_PROJECT_ID = "$REACT_APP_CONNECT_WALLET_PROJECT_ID";
window.REACT_APP_BRIDGE_API_URI = "$REACT_APP_BRIDGE_API_URI";
window.REACT_APP_ROLLUPSCAN_API_URI = "$REACT_APP_ROLLUPSCAN_API_URI";
window.REACT_APP_CHAIN_ID_L1 = "$REACT_APP_CHAIN_ID_L1";
window.REACT_APP_CHAIN_ID_L2 = "$REACT_APP_CHAIN_ID_L2";
window.REACT_APP_EXTERNAL_RPC_URI_L1 = "$REACT_APP_EXTERNAL_RPC_URI_L1";
window.REACT_APP_EXTERNAL_RPC_URI_L2 = "$REACT_APP_EXTERNAL_RPC_URI_L2";
window.REACT_APP_EXTERNAL_EXPLORER_URI_L1 = "$REACT_APP_EXTERNAL_EXPLORER_URI_L1";
window.REACT_APP_EXTERNAL_EXPLORER_URI_L2 = "$REACT_APP_EXTERNAL_EXPLORER_URI_L2";
window.REACT_APP_L1_ETH_GATEWAY_PROXY_ADDR = "$REACT_APP_L1_ETH_GATEWAY_PROXY_ADDR";
window.REACT_APP_L2_ETH_GATEWAY_PROXY_ADDR = "$REACT_APP_L2_ETH_GATEWAY_PROXY_ADDR";
window.REACT_APP_L1_WETH_GATEWAY_PROXY_ADDR = "$REACT_APP_L1_WETH_GATEWAY_PROXY_ADDR";
window.REACT_APP_L2_WETH_GATEWAY_PROXY_ADDR = "$REACT_APP_L2_WETH_GATEWAY_PROXY_ADDR";
window.REACT_APP_L1_CUSTOM_ERC20_GATEWAY_PROXY_ADDR = "$REACT_APP_L1_CUSTOM_ERC20_GATEWAY_PROXY_ADDR";
window.REACT_APP_L2_CUSTOM_ERC20_GATEWAY_PROXY_ADDR = "$REACT_APP_L2_CUSTOM_ERC20_GATEWAY_PROXY_ADDR";
window.REACT_APP_L1_USDC_GATEWAY_PROXY_ADDR = "$REACT_APP_L1_USDC_GATEWAY_PROXY_ADDR";
window.REACT_APP_L2_USDC_GATEWAY_PROXY_ADDR = "$REACT_APP_L2_USDC_GATEWAY_PROXY_ADDR";
window.REACT_APP_L1_DAI_GATEWAY_PROXY_ADDR = "$REACT_APP_L1_DAI_GATEWAY_PROXY_ADDR";
window.REACT_APP_L2_DAI_GATEWAY_PROXY_ADDR = "$REACT_APP_L2_DAI_GATEWAY_PROXY_ADDR";
window.REACT_APP_L1_LIDO_GATEWAY_PROXY_ADDR = "$REACT_APP_L1_LIDO_GATEWAY_PROXY_ADDR";
window.REACT_APP_L2_LIDO_GATEWAY_PROXY_ADDR = "$REACT_APP_L2_LIDO_GATEWAY_PROXY_ADDR";
window.REACT_APP_L1_PUFFER_GATEWAY_PROXY_ADDR = "$REACT_APP_L1_PUFFER_GATEWAY_PROXY_ADDR";
window.REACT_APP_L2_PUFFER_GATEWAY_PROXY_ADDR = "$REACT_APP_L2_PUFFER_GATEWAY_PROXY_ADDR";
window.REACT_APP_L1_STANDARD_ERC20_GATEWAY_PROXY_ADDR = "$REACT_APP_L1_STANDARD_ERC20_GATEWAY_PROXY_ADDR";
window.REACT_APP_L2_STANDARD_ERC20_GATEWAY_PROXY_ADDR = "$REACT_APP_L2_STANDARD_ERC20_GATEWAY_PROXY_ADDR";
window.REACT_APP_L1_SCROLL_MESSENGER = "$REACT_APP_L1_SCROLL_MESSENGER";
window.REACT_APP_L2_SCROLL_MESSENGER = "$REACT_APP_L2_SCROLL_MESSENGER";
window.REACT_APP_L1_GATEWAY_ROUTER_PROXY_ADDR = "$REACT_APP_L1_GATEWAY_ROUTER_PROXY_ADDR";
window.REACT_APP_L2_GATEWAY_ROUTER_PROXY_ADDR = "$REACT_APP_L2_GATEWAY_ROUTER_PROXY_ADDR";
window.REACT_APP_L1_GAS_PRICE_ORACLE = "$REACT_APP_L1_GAS_PRICE_ORACLE";
window.REACT_APP_SCROLL_CHAIN = "$REACT_APP_SCROLL_CHAIN";
window.REACT_APP_L1_MESSAGE_QUEUE = "$REACT_APP_L1_MESSAGE_QUEUE";
window.REACT_APP_L1_MESSAGE_QUEUE_WITH_GAS_PRICE_ORACLE = "$REACT_APP_L1_MESSAGE_QUEUE_WITH_GAS_PRICE_ORACLE";
window.REACT_APP_L1_BATCH_BRIDGE_GATEWAY_PROXY_ADDR = "$REACT_APP_L1_BATCH_BRIDGE_GATEWAY_PROXY_ADDR";
EOF

# nginx -g daemon off;
nginx -g "daemon off;"