# redirects in staging env

# these two redirects are for MAIN only, as a transitional help
# TODO: change rpc redirect to staging
# [[redirects]]
#   from = "/l1/*"
#   to = "https://staging-prealpha-rpc.scroll.io/l1/:splat"
#   status = 200
# [[redirects]]
#   from = "/l2/*"
#   to = "https://staging-prealpha-rpc.scroll.io/l2/:splat"
#   status = 200
[[redirects]]
  from = "/l1/*"
  to = "https://prealpha-rpc.scroll.io/l1/:splat"
  status = 200
[[redirects]]
  from = "/l2/*"
  to = "https://prealpha-rpc.scroll.io/l2/:splat"
  status = 200

[[redirects]]
  from = "/faucetapi/*"
  to = "https://staging-prealpha-api.scroll.io/faucet/:splat"
  status = 200
[[redirects]]
  from = "/bridgeapi/*"
  to = "https://staging-prealpha-api.scroll.io/bridgehistory/api/:splat"
  status = 200
