import Next from "next"

declare global {
  namespace NodeJS {
    interface ProcessEnv {
      NEXT_PUBLIC_MAIN_ENVIRONMENT: string
      NEXT_PUBLIC_ETH_SYMBOL: string
      NEXT_PUBLIC_PREFIX_CLS: string
      NEXT_PUBLIC_SENTRY_DSN: string
      NEXT_PUBLIC_GOOGLE_ANALYTICS_ID: string
      NEXT_PUBLIC_CONNECT_WALLET_PROJECT_ID: string
      NEXT_PUBLIC_UNIFRA_API_KEY: string
      NEXT_PUBLIC_NFT_VIEWER_URL: string
      NEXT_PUBLIC_NFT_API_URI: string
      NEXT_PUBLIC_SCROLL_ENVIRONMENT: string
      NEXT_PUBLIC_API_BASE_URI: string
      NEXT_PUBLIC_BRIDGE_API_URI: string
      NEXT_PUBLIC_ROLLUPSCAN_API_URI: string
      NEXT_PUBLIC_CHAIN_ID_L1: string
      NEXT_PUBLIC_CHAIN_ID_L2: string
      NEXT_PUBLIC_EXTERNAL_RPC_URI_L1: string
      NEXT_PUBLIC_EXTERNAL_RPC_URI_L2: string
      NEXT_PUBLIC_EXTERNAL_EXPLORER_URI_L1: string
      NEXT_PUBLIC_EXTERNAL_EXPLORER_URI_L2: string
      NEXT_PUBLIC_EXTERNAL_EXPLORER_URI_DORA: string
      NEXT_PUBLIC_ETHERSCAN_L2: string
      NEXT_PUBLIC_L2_SCAN_URI: string
      NEXT_PUBLIC_L1_ETH_GATEWAY_PROXY_ADDR: string
      NEXT_PUBLIC_L2_ETH_GATEWAY_PROXY_ADDR: string
      NEXT_PUBLIC_L1_WETH_GATEWAY_PROXY_ADDR: string
      NEXT_PUBLIC_L2_WETH_GATEWAY_PROXY_ADDR: string
      NEXT_PUBLIC_L1_CUSTOM_ERC20_GATEWAY_PROXY_ADDR: string
      NEXT_PUBLIC_L2_CUSTOM_ERC20_GATEWAY_PROXY_ADDR: string
      NEXT_PUBLIC_L1_USDC_GATEWAY_PROXY_ADDR: string
      NEXT_PUBLIC_L2_USDC_GATEWAY_PROXY_ADDR: string
      NEXT_PUBLIC_L1_DAI_GATEWAY_PROXY_ADDR: string
      NEXT_PUBLIC_L2_DAI_GATEWAY_PROXY_ADDR: string
      NEXT_PUBLIC_L1_LIDO_GATEWAY_PROXY_ADDR: string
      NEXT_PUBLIC_L2_LIDO_GATEWAY_PROXY_ADDR: string
      NEXT_PUBLIC_L1_PUFFER_GATEWAY_PROXY_ADDR: string
      NEXT_PUBLIC_L2_PUFFER_GATEWAY_PROXY_ADDR: string
      NEXT_PUBLIC_L1_STANDARD_ERC20_GATEWAY_PROXY_ADDR: string
      NEXT_PUBLIC_L2_STANDARD_ERC20_GATEWAY_PROXY_ADDR: string
      NEXT_PUBLIC_L1_SCROLL_MESSENGER: string
      NEXT_PUBLIC_L2_SCROLL_MESSENGER: string
      NEXT_PUBLIC_L1_GATEWAY_ROUTER_PROXY_ADDR: string
      NEXT_PUBLIC_L2_GATEWAY_ROUTER_PROXY_ADDR: string
      NEXT_PUBLIC_L1_GAS_PRICE_ORACLE: string
      NEXT_PUBLIC_L2_GAS_PRICE_ORACLE: string
      NEXT_PUBLIC_SCROLL_CHAIN: string
      NEXT_PUBLIC_SCROLL_ORIGINS_NFT: string
      NEXT_PUBLIC_SCROLL_ORIGINS_NFT_V2: string
      NEXT_PUBLIC_VERSION: string
      NEXT_PUBLIC_L1_MESSAGE_QUEUE_WITH_GAS_PRICE_ORACLE: string
    }
  }
}
