import { Box, Typography } from "@mui/material"
import { styled } from "@mui/system"

const Container = styled(Box)(({ theme }) => ({
  padding: "14rem 6rem",
  [theme.breakpoints.down("md")]: {
    padding: "8rem 2rem",
  },
  "& *": {
    fontSize: "2rem",
    textAlign: "justify",
    [theme.breakpoints.down("sm")]: {
      fontSize: "1.6rem",
    },
  },
  "& h1, & h2, & h3": {
    fontWeight: "bold",
    marginBottom: "2.8rem",
    [theme.breakpoints.down("md")]: {
      marginBottom: "2rem",
    },
  },
  "& p": {
    marginBottom: "1.6rem",
    "+ h1, + h2, + h3": {
      marginTop: "2.8rem",
      [theme.breakpoints.down("md")]: {
        marginTop: "2rem",
      },
    },
  },
  "& ul": {
    listStyle: "inside",
    "& li": {
      margin: "1.6rem 0",
      [theme.breakpoints.down("md")]: {
        margin: "1rem 0",
      },
    },
    "+ h1, + h2, + h3": {
      marginTop: "2.8rem",
      [theme.breakpoints.down("md")]: {
        marginTop: "2rem",
      },
    },
  },
  [`${TitleTypography}`]: {
    fontWeight: "500",
  },
}))

const TitleTypography = styled(Typography)(({ theme }) => ({
  textAlign: "center",
}))

const DashTypography = styled("h3")(({ theme }) => ({
  "&::before": {
    content: '"-"',
    margin: "0 3rem",
    fontWeight: "normal",
    [theme.breakpoints.down("md")]: {
      margin: "0 2rem",
    },
  },
}))

const PrivacyPolicy = () => {
  return (
    <Container className="wrapper">
      <TitleTypography variant="h1">Privacy Policy For Scroll Limited</TitleTypography>
      <p>
        Last updated: March 8<sup>th</sup>, 2023
      </p>
      <p>
        This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service
        and tells You about Your privacy rights and how the law protects You.
      </p>
      <p>
        We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in
        accordance with this Privacy Policy.
      </p>
      <h1>Interpretation and Definitions</h1>
      <h2>Interpretation</h2>
      <p>
        The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall
        have the same meaning regardless of whether they appear in singular or in plural.
      </p>
      <h2>Definitions</h2>
      <p>For the purposes of this Privacy Policy:</p>
      <ul>
        <li>
          <strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.
        </li>
        <li>
          <strong>Company</strong> (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to Scroll.
        </li>
        <li>
          <strong>Cookies</strong> are small files that are placed on Your computer, mobile device or any other device by a Websites, containing the
          details of Your browsing history on that Websites among its many uses.
        </li>
        <li>
          <strong>Device</strong> means any device that can access the Service such as a computer, a cell phone or a digital tablet.
        </li>
        <li>
          <strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.
        </li>
        <li>
          <strong>Service</strong> refers to the Websites, including but not limited to, the modules and activities provided by the Websites.
        </li>
        <li>
          <strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company. It refers to
          third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to
          perform services related to the Service or to assist the Company in analyzing how the Service is used.
        </li>
        <li>
          <strong>Third-party Social Media Service</strong> refers to any Websites or any social network Websites through which a User can log in or
          create an account to use the Service.
        </li>
        <li>
          <strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service
          infrastructure itself (for example, the duration of a page visit).
        </li>
        <li>
          <strong>Websites</strong> refers to Scroll Limited’s online offerings such as the homepage and the blockchain Apps, accessible from 
          <a className="underline" href="https://scroll.io/">
            https://scroll.io/
          </a>
        </li>
        <li>
          <strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such
          individual is accessing or using the Service, as applicable.
        </li>
      </ul>
      <h1>Collecting and Using Your Personal Information</h1>
      <h2>Types of Information that Might be Collected</h2>
      <DashTypography>Personal Information</DashTypography>

      <p>
        While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify
        You. Personally identifiable information may include, but is not limited to:
      </p>
      <ul>
        <li>Email address</li>
        <li>First name and last name</li>
        <li>Phone number</li>
        <li>Address, State, Province, ZIP/Postal code, City, Country</li>
        <li>Usage Data</li>
      </ul>
      <DashTypography>Usage Information</DashTypography>
      <p>Usage Information is collected automatically when using the Service.</p>
      <p>
        Usage Information may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version,
        the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other
        diagnostic data.
      </p>
      <p>
        When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to,
        the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type
        of mobile Internet browser You use, unique device identifiers and other diagnostic data.
      </p>
      <p>
        We may also collect information that Your browser sends whenever You visit our Service or when You access the Service by or through a mobile
        device.
      </p>
      <DashTypography>Financial Information</DashTypography>
      <p>
        We may also require access to financial information, including but not limited to, transaction history, crypto wallet, and information from
        other sources
      </p>
      <DashTypography>Non-Personal Information Collected Automatically</DashTypography>
      <p>
        When you access Our Websites, we may automatically (i.e. not by registration) collect statistical information that is not personally
        identifiable (e.g. type of Internet browser and computer operating system used; domain name of the Websites from which you came; number of
        visits, average time spent, pages viewed). We may use this information and share it with affiliates and partners to measure the use of its
        Websites and improve its content.
      </p>
      <br />
      <br />

      <p>
        <strong>How We Collect Your Personal Information </strong>
      </p>
      <p>The Company collects personal information in different ways and from different resources.</p>
      <p>
        <strong>Directly From You.</strong> For example, when You:
      </p>
      <ul>
        <li>Make a transaction on Our Websites.</li>
        <li>Sign up to join Our Testnets.</li>
        <li>Sign up to receive promotional emails or text messages.</li>
        <li>Provide Your contact information for any given reason.</li>
        <li>Create or update your account.</li>
        <li>Use Our Websites’ related services and features.</li>
        <li>Submit a request to Our customer service team.</li>
        <li>Connect any external account (e.g., crypto wallet, social media) to use Our services.</li>
        <li>Interact with The Company’s social media pages.</li>
      </ul>
      <p>
        <strong>Passively. </strong>For example, when you:
      </p>
      <ul>
        <li>Visit and navigate the company’s Websites on any device.</li>
        <li>Enable location-based features on Our Websites.</li>
        <li>Receive or interact with The Company’s communications and Websites that may contain cookies or pixels.</li>
      </ul>
      <h3>Tracking Technologies and Cookies</h3>
      <p>
        We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. Tracking technologies
        used are beacons, tags, and scripts to collect and track information and to improve and analyze Our Service. The technologies We use may
        include:
      </p>
      <ul>
        <li>
          <strong>Cookies or Browser Cookies.</strong> A cookie is a small file placed on Your Device. You can instruct Your browser to refuse all
          Cookies or to indicate when a Cookie is being sent. However, if You do not accept Cookies, You may not be able to use some parts of our
          Service. Unless you have adjusted Your browser setting so that it will refuse Cookies, our Service may use Cookies.
        </li>
        <li>
          <strong>Web Beacons.</strong> Certain sections of our Service and our emails may contain small electronic files known as web beacons (also
          referred to as clear gifs, pixel tags, and single-pixel gifs) that permit the Company, for example, to count users who have visited those
          pages or opened an email and for other related Websites statistics (for example, recording the popularity of a certain section and verifying
          system and server integrity).
        </li>
      </ul>
      <p>
        Cookies can be "Persistent" or "Session" Cookies. Persistent Cookies remain on Your personal computer or mobile device when You go offline,
        while Session Cookies are deleted as soon as You close Your web browser.
      </p>
      <p>We use both Session and Persistent Cookies for the purposes set out below:</p>
      <ul>
        <li>
          <strong>Necessary / Essential Cookies</strong>
        </li>
        <li>Type: Session Cookies</li>
        <li>Administered by: Us</li>
        <li>
          Purpose: These Cookies are essential to provide You with services available through the Websites and to enable You to use some of its
          features. They help to authenticate users and prevent fraudulent use of user accounts. Without these Cookies, the services that You have
          asked for cannot be provided, and We only use these Cookies to provide You with those services.
        </li>
        <li>
          <strong>Cookies Policy / Notice Acceptance Cookies</strong>
        </li>
        <li>Type: Persistent Cookies</li>
        <li>Administered by: Us</li>
        <li>Purpose: These Cookies identify if users have accepted the use of cookies on the Websites.</li>
        <li>
          <strong>Functionality Cookies</strong>
        </li>
        <li>Type: Persistent Cookies</li>
        <li>Administered by: Us</li>
        <li>
          Purpose: these Cookies allow us to remember choices You make when You use the Websites, such as remembering your login details or language
          preference. The purpose of these Cookies is to provide You with a more personal experience and to avoid You having to re-enter your
          preferences every time You use the Websites.
        </li>
      </ul>
      <p>
        For more information about the cookies, we use and your choices regarding cookies, please visit our Cookies Policy or the Cookies section of
        our Privacy Policy.
      </p>
      <h2>Use of Your Personal Data</h2>
      <p>The Company may use Personal Data for the following purposes:</p>
      <ul>
        <li>
          <strong>To provide and maintain our Service:</strong> including but not limited to develop, improve and personalize our Service, as well as
          to monitor the usage of our Service.
        </li>
        <li>
          <strong>To manage Your Account:</strong> to manage Your registration as a user of the Service. The Personal Data You provide can give You
          access to different functionalities of the Service that are available to You as a registered user.
        </li>
        <li>
          <strong>For the performance of a contract:</strong> the development, compliance and undertaking of the purchase contract for the products,
          items or services You have purchased or of any other contract with Us through the Service.
        </li>
        <li>
          <strong>To contact You:</strong> to contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication, such
          as a mobile application's push notifications regarding updates or informative communications related to the functionalities, products or
          contracted services, including the security updates, when necessary or reasonable for their implementation.
        </li>
        <li>
          <strong>To provide You:</strong> with news, special offers and general information about other goods, services and events which we offer
          that are similar to those that you have already purchased or inquired about unless You have opted not to receive such information.
        </li>
        <li>
          <strong>To manage Your requests:</strong> to attend and manage Your requests to Us.
        </li>
        <li>
          <strong>For business transfers:</strong> we may use Your information to evaluate or conduct a merger, divestiture, restructuring,
          reorganization, dissolution, or other sale or transfer of some or all of Our assets, whether as a going concern or as part of bankruptcy,
          liquidation, or similar proceeding, in which Personal Data held by Us about our Service users is among the assets transferred.
        </li>
        <li>
          <strong>For compliance purposes:</strong> such as to prevent fraud and/or money laundering.
        </li>
        <li>
          <strong>For other purposes:</strong> we may use Your information for other purposes, such as data analysis, identifying usage trends,
          determining the effectiveness of our promotional campaigns and to evaluate and improve our Service, products, functionality, services,
          marketing and your experience.
        </li>
      </ul>
      <p>We may share Your personal information in the following situations:</p>
      <ul>
        <li>
          <strong>With Service Providers:</strong> we may share Your personal information with Service Providers to monitor and analyze the use of our
          Service, to contact You.
        </li>
        <li>
          <strong>For business transfers:</strong> we may share or transfer Your personal information in connection with, or during negotiations of,
          any merger, sale of Company assets, financing, or acquisition of all or a portion of Our business to another company.
        </li>
        <li>
          <strong>With Affiliates:</strong> we may share Your information with Our affiliates, in which case we will require those affiliates to honor
          this Privacy Policy. Affiliates include Our parent company and any other subsidiaries, joint venture partners or other companies that We
          control or that are under common control with Us.
        </li>
        <li>
          <strong>With business partners:</strong> we may share Your information with Our business partners to offer You certain products, services or
          promotions.
        </li>
        <li>
          <strong>With other users:</strong> when You share personal information or otherwise interact in the public areas with other users, such
          information may be viewed by all users and may be publicly distributed outside. If You interact with other users or register through a
          Third-Party Social Media Service, Your contacts on the Third-Party Social Media Service may see Your name, profile, pictures and description
          of Your activity. Similarly, other users will be able to view descriptions of Your activity, communicate with You and view Your profile.
        </li>
        <li>
          <strong>With Your consent:</strong> we may disclose Your personal information for any other purpose with Your consent.
        </li>
      </ul>
      <h2>Retention of Your Personal Data</h2>
      <p>
        The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain
        and use Your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data
        to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.
      </p>
      <p>
        The Company will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period of time, except
        when this data is used to strengthen the security or to improve the functionality of Our Service, or We are legally obligated to retain this
        data for longer time periods.
      </p>
      <h2>Transfer of Your Personal Data</h2>
      <p>
        Data collected, in the course of the Company’s business activities, including in connection with some client services, as well as on the
        Website such as personal information may be transferred from time to time to Scroll subsidiaries and affiliates and their personnel across our
        global network, as well as to our third-party service providers located throughout the world, including in countries where the local law may
        grant you fewer rights than you have in your own country. Additionally, the Website may be viewed and hosted by the Company and our
        third-party service providers anywhere in the world. Where required by applicable laws, we have put in place legal mechanisms designed to
        ensure adequate data protection of your personal data that is processed by Our subsidiaries, affiliates and third-party service providers,
        including the transfer of your personal data to countries other than the one in which you reside. If you would like more information about
        these legal mechanisms, please contact us at the email address below, By using any of the Websites and providing information on any of them,
        you voluntarily consent to such trans-border transfer and hosting of such information.
      </p>
      <h2>Delete Your Personal Data</h2>
      <p>You have the right to delete or request that We assist in deleting the Personal Data that We have collected about You.</p>
      <p>Our Service may give You the ability to delete certain information about You from within the Service.</p>
      <p>
        You may update, amend, or delete Your information at any time by signing in to Your Account, if you have one, and visiting the account
        settings section that allows you to manage Your personal information. You may also contact Us to request access to, correct, or delete any
        personal information that You have provided to Us.
      </p>
      <p>Please note, however, that We may need to retain certain information when we have a legal obligation or lawful basis to do so.</p>
      <h2>Disclosure of Your Personal Data</h2>
      <h3>Business Transactions</h3>
      <p>
        If the Company is involved in a merger, acquisition or asset sale, Your Personal Data may be transferred. We will provide notice before Your
        Personal Data is transferred and becomes subject to a different Privacy Policy.
      </p>
      <h3>Law enforcement</h3>
      <p>
        Under certain circumstances, the Company may be required to disclose Your Personal Data if required to do so by law or in response to valid
        requests by public authorities (e.g. a court or a government agency).
      </p>
      <h3>Other legal requirements</h3>
      <p>The Company may disclose Your Personal Data in the good faith belief that such action is necessary to:</p>
      <ul>
        <li>Comply with a legal obligation</li>
        <li>Protect and defend the rights or property of the Company</li>
        <li>Prevent or investigate possible wrongdoing in connection with the Service</li>
        <li>Protect the personal safety of Users of the Service or the public</li>
        <li>Protect against legal liability</li>
      </ul>
      <h2>Security of Your Personal Data</h2>
      <p>
        The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic
        storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute
        security.
      </p>
      <h1>Links to Other Websites</h1>
      <p>
        Our Service may contain links to other Websites that are not operated by Us. If You click on a third-party link, You will be directed to that
        third-party's site. We strongly advise You to review the Privacy Policy of every site You visit.
      </p>
      <p>We have no control over and assume no responsibility for the content, privacy policies or practices of any third-party sites or services.</p>
      <h1>Changes to this Privacy Policy</h1>
      <p>We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.</p>
      <p>
        We will let You know via email and/or a prominent notice on Our Service, prior to the change becoming effective and update the "Last updated"
        date at the top of this Privacy Policy.
      </p>
      <p>
        You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted
        on this page.
      </p>
      <h1>Contact Us</h1>
      <p>
        If you have any questions about this Privacy Policy, including but not limited to, Your rights under this Policy, filing a complaint or
        requesting that We update, delete or restrict the use of Your Personal Data, You can contact Our Data Protection Officer at{" "}
        <a className="underline" href="mailto:hi@scroll.io">
          hi@scroll.io
        </a>
        .
      </p>
    </Container>
  )
}

export default PrivacyPolicy
