name: Auto Merge
on:
  pull_request:
    branches:
      - "main"
      - "staging"
    types:
      - labeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  pull_request_review:
    types:
      - submitted
  status: {}
jobs:
  automerge:
    if: |
      startsWith(github.event.head_commit.message , 'ci:') &&
      endsWith(github.event.head_commit.message , '[bot]')
    runs-on: ubuntu-latest
    steps:
      - id: automerge
        name: automerge
        uses: "pascalgn/automerge-action@22948e0bc22f0aa673800da838595a3e7347e584"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_METHOD: "squash"
