name: Auto Approve
on:
  pull_request_target:
    branches:
      - "main"
      - "staging"
jobs:
  build:
    if: |
      startsWith(github.event.head_commit.message , 'ci:') &&
      endsWith(github.event.head_commit.message , '[bot]')
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: hmarr/auto-approve-action@de8ae18c173c131e182d4adf2c874d8d2308a85b
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
