# auto approve any pr that has ` [bot]` at the end of the pr title
# note the first character in ` [bot]` is a thin space https://www.wikiwand.com/en/Thin_space
name: Auto Approve
on:
  pull_request:
    branches:
      - sepolia
jobs:
  build:
    if: |
      endsWith(github.event.pull_request.title, ' [bot]')
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: hmarr/auto-approve-action@de8ae18c173c131e182d4adf2c874d8d2308a85b
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
