# when there's new PR merge production back to develop branch get merged
# create a pr from ci/_bump-version to develop branch
# with a commit that bumps the version in package.json
name: "Bump Version"

on:
  pull_request:
    branches:
      - develop
    types:
      - closed

jobs:
  bump-version:
    if: |
      success() && contains(github.event.pull_request.title, 'ci: merge production branch back to develop [bot]')
    name: "Bump version on develop"
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout source code"
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}
          ref: ${{ github.ref }}

      - name: "cat package.json"
        run: cat ./package.json

      - name: "Automated Version Bump"
        id: version-bump
        uses: "phips28/gh-action-bump-version@25cd8ffb8ec95f16f83a8dac9557a845e4fa9e21"
        with:
          tag-prefix: ""
          skip-push: "true"
          commit-message: "ci: version bump to {{version}} [bot]"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get Version Bump Commit Message
        run: echo "::set-output name=title::$(git log --pretty=format:"%s" -1)"
        id: get-version-bump-commit-message

      - name: Create Pull Request for develop
        uses: peter-evans/create-pull-request@2b011faafdcbc9ceb11414d64d0573f37c774b04
        with:
          token: ${{ secrets.WRITE_TOKEN }}
          delete-branch: true
          branch: ci/_bump-version
          title: ${{ steps.get-version-bump-commit-message.outputs.title }}
          labels: "bot/bump-version, automerge"
          body: ""
